// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPM9jY6LZCIFL-OJftJPF1PBDNmJ1AAzo',
    appId: '1:92194847659:web:f523d9e1f642630106b0ee',
    messagingSenderId: '92194847659',
    projectId: 'hormony-52bba',
    authDomain: 'hormony-52bba.firebaseapp.com',
    storageBucket: 'hormony-52bba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB12tLZ5n473FtsAisql162l-8SHWa9hkU',
    appId: '1:92194847659:android:7b157a4da109f95906b0ee',
    messagingSenderId: '92194847659',
    projectId: 'hormony-52bba',
    storageBucket: 'hormony-52bba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGyA5dgmx2pR8_C7WtgdlUvcAuTdwRxkY',
    appId: '1:92194847659:ios:0d248423a8f9987806b0ee',
    messagingSenderId: '92194847659',
    projectId: 'hormony-52bba',
    storageBucket: 'hormony-52bba.appspot.com',
    iosBundleId: 'com.enco.zen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGyA5dgmx2pR8_C7WtgdlUvcAuTdwRxkY',
    appId: '1:92194847659:ios:0d248423a8f9987806b0ee',
    messagingSenderId: '92194847659',
    projectId: 'hormony-52bba',
    storageBucket: 'hormony-52bba.appspot.com',
    iosBundleId: 'com.enco.zen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPM9jY6LZCIFL-OJftJPF1PBDNmJ1AAzo',
    appId: '1:92194847659:web:7c9c36502c4dc7c906b0ee',
    messagingSenderId: '92194847659',
    projectId: 'hormony-52bba',
    authDomain: 'hormony-52bba.firebaseapp.com',
    storageBucket: 'hormony-52bba.appspot.com',
  );

}